### ISSUE TITLE
希望加入搜索设置保存

### ISSUE THREAD

**Issue by poisonoff** [bynil/sov2ex#1]
RT

**Comment by Kenshin** [comment]
感谢反馈~
下个版本会加入此功能。  😊

**Comment by Zhang-Siyang** [comment]
@Kenshin 现在OpenSearch上线了，可否把「记住搜索设定（如按时间排序）」写入到Cookie里？

可参考 https://cn.bing.com/ 的做法：
使用`国内版`搜索后，设置`.bing.com`下，名为`ENSEARCH`的Cookie值为`BENVER=0`。反之，则是设置值为`BENVER=1`。效果便是在Chrome地址栏调用OpenSearch时能够记住上一次的选择（似乎手动指定时使用的是URL query，如此就覆盖Cookie中的值了）

嘻嘻，做好OpenSearch了，迎来下一个需求吧😊

**Comment by bynil** [comment]
> @Kenshin 现在OpenSearch上线了，可否把「记住搜索设定（如按时间排序）」写入到Cookie里？
> 
> 可参考 https://cn.bing.com/ 的做法：
> 使用`国内版`搜索后，设置`.bing.com`下，名为`ENSEARCH`的Cookie值为`BENVER=0`。反之，则是设置值为`BENVER=1`。效果便是在Chrome地址栏调用OpenSearch时能够记住上一次的选择（似乎手动指定时使用的是URL query，如此就覆盖Cookie中的值了）
> 
> 嘻嘻，做好OpenSearch了，迎来下一个需求吧😊

记住搜索设定是核心改进，应该很快会加进来。感觉 LocalStorage 比 Cookie 更好。

**Comment by Kenshin** [comment]
@Zhang-Siyang @bynil 

okay 不过，我也建议使用 LS 方式。
