### ISSUE TITLE
设置 默认 搜索某个时间的帖子

### ISSUE THREAD

**Issue by daivvv** [bynil/sov2ex#10]
希望这些设置能够保存下来,省得每次需要输入

![image](https://user-images.githubusercontent.com/38233144/39620676-814d3ef0-4fbe-11e8-824c-6f98f5d5f5de.png)

**Comment by Kenshin** [comment]
我记得有这个功能… （也有可能记错了… 😂

**Comment by bynil** [comment]
@Kenshin 没有做...

**Comment by Kenshin** [comment]
😱😰
好像要补不少功能了…
