### ISSUE TITLE
关于数据的索引

### ISSUE THREAD

**Issue by RitterHou** [bynil/sov2ex#13]
你好，我看了源代码似乎没有看到实现数据索引的代码，请问这部分的代码是在怎么实现的呢？谢谢！

**Comment by bynil** [comment]
数据塞到 Elasticsearch 里面了 https://github.com/bynil/v2ex-crawler/blob/master/data/data.py#L151

**Comment by bynil** [comment]
后面再查询的话构建 ES 的查询语句就行，麻烦的地方在于设计好存储结构和评分逻辑。
