### ISSUE TITLE
想做一次更新

### ISSUE THREAD

**Issue by bynil** [bynil/sov2ex#14]
几个 issue 里提到的功能可以完成掉：

1. 把用户 ID 作为搜索条件。
2. 浏览器持久保存 sov2ex.com 的搜索设置。
3. 节点下所有主题按质量排序。

**Comment by bynil** [comment]
@Kenshin 你那里最近有空吗？

**Comment by Kenshin** [comment]
8月底（估计要到 9 月初）以及之后应该没问题~

**Comment by FreeyW** [comment]
强烈支持2 我比较习惯按照时间排序搜索，每次都要重新选择一次
感谢up主，sov2ex非常好用

**Comment by bynil** [comment]
> 强烈支持2 我比较习惯按照时间排序搜索，每次都要重新选择一次
> 感谢up主，sov2ex非常好用

哈哈哈哈哈你是不是B站逛太多了。外面裹的 api 层我准备用 Golang 重新写，会尽快。

**Comment by bynil** [comment]
这个 issue 已经三个月过去了？？？我还没开动...

**Comment by bynil** [comment]
正在研究 Golang 的 driver

**Comment by bynil** [comment]
@Kenshin 我用 Golang 重写了后端 API，主题作者的参数已经加上了，你最近有空更新一下前端吗？把几个小的遗留问题解决掉。可以考虑新建一个前端的 repo。

**Comment by Kenshin** [comment]
> @Kenshin 我用 Golang 重写了后端 API，主题作者的参数已经加上了，你最近有空更新一下前端吗？把几个小的遗留问题解决掉。可以考虑新建一个前端的 repo。

前端更改的针对 username 的过滤，是吧？ API 接口没有变化？下周我找个时间来更新下，如何？

**Comment by bynil** [comment]
> > @Kenshin 我用 Golang 重写了后端 API，主题作者的参数已经加上了，你最近有空更新一下前端吗？把几个小的遗留问题解决掉。可以考虑新建一个前端的 repo。
> 
> 前端更改的针对 username 的过滤，是吧？ API 接口没有变化？下周我找个时间来更新下，如何？

API 里新加了一个 username 参数，可以看[更新后的文档 ](https://github.com/bynil/sov2ex/blob/v2/API.md)。`浏览器持久保存 sov2ex.com 的搜索设置`这次能做掉吗？

**Comment by Kenshin** [comment]
> `username` API

 👌 

> `浏览器持久保存 sov2ex.com 的搜索设置`

做掉？不需要这个功能了？

**Comment by bynil** [comment]
> > `username` API
> 
> 👌
> 
> > `浏览器持久保存 sov2ex.com 的搜索设置`
> 
> 做掉？不需要这个功能了？

就是完成掉......
