### ISSUE TITLE
前端的源码能公开吗？

### ISSUE THREAD

**Issue by RockNHawk** [Bynil/sov2ex#15]
sov2ex 经常用，感谢提供免费方便的 v2 搜索！
今天想基于 elasticsearch 做一个通用站内搜索，前端想基于 sov2ex 的代码进行开发，不知可有发布前端源码的计划呢～

**Comment by bynil** [comment]
https://github.com/Kenshin/sov2ex

**Comment by RockNHawk** [comment]
@bynil 十分感谢！！！
