### ISSUE TITLE
期望增加两个功能：opensearch、结果过滤【虽然已经长久咕咕，但我还要提issue】

### ISSUE THREAD

**Issue by Zhang-Siyang** [Bynil/sov2ex#16]
关于opensearch的定义您可以看看这几个链接：
http://www.opensearch.org/Home
https://www.v2ex.com/t/57663
https://www.v2ex.com/t/395264

我期望的结果过滤是这样的：

使用正则或关键词避过某些节点或用户

我比较关注避开节点的功能

**Comment by bynil** [comment]
1. OpenSearch 里支持复杂规则的话看起来要对 Elasticsearch 的查询做点翻译工作？这个工作量不知道多大；
2. 过滤某些人或节点很好做，可以加上；
3. 这个项目的确是咕咕了快两年，但不会丢的。

**Comment by Kenshin** [comment]
竟然快两年了，好快！

**Comment by bynil** [comment]
@Zhang-Siyang 正则放到搜索里太吃性能了，直接精准匹配可以解决你的需求吗？

**Comment by bynil** [comment]
@Kenshin opensearch 做好了， index.html 的 head 里记得加入以下内容：

```
<link rel="search" type="application/opensearchdescription+xml" href="//sov2ex.oss-cn-shanghai.aliyuncs.com/opensearch.xml" title="SOV2EX" />
```

**Comment by Kenshin** [comment]
> @Kenshin opensearch 做好了， index.html 的 head 里记得加入以下内容：

 👌

**Comment by Zhang-Siyang** [comment]
> @Zhang-Siyang 正则放到搜索里太吃性能了，直接精准匹配可以解决你的需求吗？

我本想的是在前端处理正则，这样就没什么运算压力了吧？另外不知道您说的精准匹配是什么意思？

**Comment by bynil** [comment]
> > @Zhang-Siyang 正则放到搜索里太吃性能了，直接精准匹配可以解决你的需求吗？
> 
> 我本想的是在前端处理正则，这样就没什么运算压力了吧？另外不知道您说的精准匹配是什么意思？

参考现在的 [API 设计](https://github.com/bynil/sov2ex/blob/v2/API.md)，避开节点要传入准确的节点名称。

前端是纯展示的，干不了这活，需要引擎层面做。

**Comment by bynil** [comment]
OpenSearch 有了。

过滤节点可以用减号去作为搜索条件。
