### ISSUE TITLE
建议：在搜索结果页面进行第2次搜索时，保留第1次搜索的配置

### ISSUE THREAD

**Issue by cjinchi** [Bynil/sov2ex#18]
首先非常感谢这个很好用的项目，对我个人来说特别方便

我遇到的问题是：
第1步：在sov2ex.com搜索1000xm3，并选择按“发帖时间”排序，会跳转到https://www.sov2ex.com/?q=1000xm3&sort=created
第2步：在1000xm3的搜索结果页面里，重新搜索qc30，会跳转到https://www.sov2ex.com/?q=qc30 ，也就是“sort=created”这个配置消失了

如果在1000xm3的界面展开一下搜索配置，再搜索qc30，就能跳转到https://www.sov2ex.com/?q=1000xm3&sort=created

**Comment by Kenshin** [comment]
谢谢反馈，我下周会看下这个问题。

同时 @bynil 下周我找个开工。拖太久了，我自己的事情基本上解决了。😅

**Comment by bynil** [comment]
这个和 #1 是同一个问题，搜索配置丢了。

**Comment by bynil** [comment]
> 谢谢反馈，我下周会看下这个问题。
> 
> 同时 @bynil 下周我找个开工。拖太久了，我自己的事情基本上解决了。😅

辛苦你了~

**Comment by popokcn** [comment]
最好能设置默认时间排序，或者可以按个人设置，配置可以保存在cookie里，一般搜索基本都是想看最新的帖子，每次搜索结果需要重新选择时间排序，然后再搜一次，挺麻烦的。

**Comment by bynil** [comment]
> 最好能设置默认时间排序，或者可以按个人设置，配置可以保存在cookie里，一般搜索基本都是想看最新的帖子，每次搜索结果需要重新选择时间排序，然后再搜一次，挺麻烦的。

@Kenshin 又有朋友来催你啦

**Comment by bynil** [comment]
这个功能现在有了。
