### ISSUE TITLE
Cannot reverse filter by multiple node names

### ISSUE THREAD

**Issue by Deardrops** [Bynil/sov2ex#20]
![image](https://user-images.githubusercontent.com/9463871/81768746-608aa080-950e-11ea-90a2-f92a3065cb6d.png)

Expected search results without node `酷工作` and `求职`,
But still got the result in node `求职`。

![image](https://user-images.githubusercontent.com/9463871/81768880-b52e1b80-950e-11ea-903d-5899589ea407.png)

**Comment by bynil** [comment]
Fixed by https://github.com/bynil/sov2ex/commit/f9bbf44db6c9df58689b11eeb4fdb83eef4ad61e

Thank you.
