### ISSUE TITLE
无法自动定位到新加载内容的第一条

### ISSUE THREAD

**Issue by cla55ic** [Bynil/sov2ex#23]
列出搜索结果后，点击“加载更多”按钮，没有定位在新加载内容的第一条。
导致在加载新内容前，必须记住当前的最后一条内容，在加载后，手动往上翻找到新加载内容的第一条。

**Comment by bynil** [comment]
好像是 Chrome 新版本引入的问题，得麻烦 @Sneezry 看看。

**Comment by bynil** [comment]
已更新。
