### ISSUE TITLE
能否增加查询结果排序（时间倒序）？

### ISSUE THREAD

**Issue by jowenz** [Bynil/sov2ex#25]
能否增加查询结果排序（时间倒序）？有时搜索的内容是16年17年，时间隔的有点远

**Comment by jowenz** [comment]
重新找一下，好像已经有这个功能 了，在不太明显的位置

**Comment by bynil** [comment]
![image](https://user-images.githubusercontent.com/3390634/100070979-8279be00-2e75-11eb-9af2-8824ffbbd080.png)

可以按发帖时间排序也可以只筛选指定起止日期的内容。

**Comment by vfr456** [comment]
如果从v2ex直接搜索，没办法默认通过时间排序。
![图片](https://github.com/bynil/sov2ex/assets/20488369/0487a189-8bf1-4ffc-a480-615cc7fd5f15)

**Comment by bynil** [comment]
> 如果从v2ex直接搜索，没办法默认通过时间排序。 ![图片](https://private-user-images.githubusercontent.com/20488369/329847862-0487a189-8bf1-4ffc-a480-615cc7fd5f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjcwMDEsIm5iZiI6MTcxNTUyNjcwMSwicGF0aCI6Ii8yMDQ4ODM2OS8zMjk4NDc4NjItMDQ4N2ExODktOGJmMS00ZmZjLWE0ODAtNjE1Y2M3ZmQ1ZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE1MTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZWJmZDE0YzQzZmE1OGUxYWRkN2VmMWEyZTQ0OGJjYzE5ZmI2NmE5NzdiYzg5YzZkMDExOTY0NDg5MmNjZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.diHxY9ybnQkPDgDMMVOX9doH59zm5rwTogcldOIWUQI)

V2EX 直接打开关键词的页面，没有触发前端页面保存的配置。前端下一版本更新时看看咋解决。
