### ISSUE TITLE
网站停止扫描新文章了吗？

### ISSUE THREAD

**Issue by laycher** [Bynil/sov2ex#27]
我搜索关键字发现最新的文章都是1月份的？
我特意在v2ex中新发的文章中的关键字进行搜索，最新的就是1月份的？

不再更新了吗？

比如搜索树莓派
https://www.sov2ex.com/?q=%E6%A0%91%E8%8E%93%E6%B4%BE&xdown-timestamp=1609999691329&xdown-version=1.0.5&sort=created&version=1.0.1&xdown-timestamp=1609999691329&lte=1613606400000&gte=1612137600000&xdown-version=1.0.5&version=1.0.1

指定了日期，但是提示没有找到任何文章。

以下这个是2月17日发布的，没有搜索到？
https://www.v2ex.com/t/753710

**Comment by bynil** [comment]
爬虫那边不太对劲，现在缓慢恢复中。谢谢提醒。

出口 IP 也不够用了，后面这块要重新整理一下。
