### ISSUE TITLE
sov2ex 爬虫服务迁移

### ISSUE THREAD

**Issue by bynil** [Bynil/sov2ex#28]
由于 v2ex.com 域名遭遇 DNS 污染及 SNI 阻断，sov2ex 原本直接运行在大陆境内的爬虫服务已经无法检索新的帖子内容，目前处于故障状态。

根据历史日志，可追溯的最早故障时间在北京时间 2021-04-10 20:59:19。

我正在寻找最低成本解决这个问题的方式。

**Comment by Kenshin** [comment]
v2 又出什么问题了？还是被牵连了？

**Comment by bynil** [comment]
> v2 又出什么问题了？还是被牵连了？

现在墙内彻底无法访问。

**Comment by bynil** [comment]
暂时通过代理解决。
