### ISSUE TITLE
很喜欢你们的网站，做了一个FireFox的add-on，方便使用

### ISSUE THREAD

**Issue by sven-w** [bynil/sov2ex#3]
各位大神想必有更方便的使用办法，交流交流
https://addons.mozilla.org/zh-CN/firefox/addon/v2ex-search/

**Comment by bynil** [comment]
我原本以为是像 v2ex plus 那样在 v2ex.com 页面上增加了功能，试了下才知道是地址栏的扩展。对于有需求的朋友来说可以省一个步骤还是挺实用的，谢谢~

**Comment by Kenshin** [comment]
不错的想法~

建议：
- 最好有截图；
- 有更详细的描述；
- 顺便上架 Chrome webstore  😄
