### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jerry011235** [bynil/sov2ex#5]
你好，目前“查询结果排序”,默认为“权重”,如果手动选中"发帖时间",则还要点击右侧的搜索按钮,才能搜索。
希望改成：当手动选中"发帖时间"后，马上就搜索，无需再次点击右侧的搜索按钮。

**Comment by bynil** [comment]
这个改进有点违背常规的使用习惯。更好的方式是让浏览器记住上次的搜索选项：#1

**Comment by jerry011235** [comment]
让浏览器记住上次的搜索选项 +1
谢谢了!

**Comment by Zhang-Siyang** [comment]
@bynil 您好，请问这个功能（记住上次排序规则）实现了吗？我刚才试着发现还是不能记住上一次搜索时的偏好。

能使用V2EX的语言设定那样，搜索设定存在Cookie里吗？这样自动就发送到后端了，代码想来应该也好写多了

**Comment by bynil** [comment]
@Zhang-Siyang 这个要改前端代码，还没做（主要是我不会）。我争取今年内喊上 @Kenshin 再做一次更新。

**Comment by Kenshin** [comment]
嗯嗯，冒个泡。
是该更新一波了～
