### ISSUE TITLE
建议首页及所有文档里提到 V2EX 时请使用全大写形式

### ISSUE THREAD

**Issue by livid** [bynil/sov2ex#6]
正确形式：

**V2EX**

错误形式：

* v2ex
* V2ex

---

谢谢。

**Comment by bynil** [comment]
把已有的问题修正了，前端源码里的等下次@Kenshin 更新时再改一下。

**Comment by Kenshin** [comment]
@bynil @livid
近期在休假，工作时间比较随机，尽快修复这些问题。

另外， 是不是也需要统一为 SOV2EX ？

**Comment by bynil** [comment]
@Kenshin 现在文档和页面上已经在使用 SOV2EX 了，项目名可以小写无妨。
