### ISSUE TITLE
V2EX Plus 早几个版本已经集成

### ISSUE THREAD

**Issue by sciooga** [bynil/sov2ex#8]
很多朋友，记得包括作者也曾提到希望 V2EX Plus 这款扩展也集成这个搜索，早几个版本我们已经添加，设置中可以开启，开启后 V 站顶部的搜索即替换成 sov2ex，并且有划词右键搜索的功能。

![image](https://user-images.githubusercontent.com/9958281/38074514-891aec28-3361-11e8-871f-00446aac9e83.png)

**Comment by bynil** [comment]
非常感谢~
这个扩展我一直在用，本来想自己动手提 PR 的结果一直在 TODO 里了。
我来更新一波 README

**Comment by sciooga** [comment]
不客气，一直忙，忘了过来说一声 : )
