### ISSUE TITLE
枚举值类型补充

### ISSUE THREAD

**Issue by ghuiii** [bynil/sov2ex#9]
![image](https://user-images.githubusercontent.com/5203798/38162655-a5d11e8e-3517-11e8-875d-afdd03489748.png)
建议对可能存在多个枚举值的字段，列出来所有可能的值，比如上面的 **_type** 及 **_index** 我的理解_type至少还应该包含代表`节点`的的类型。
感谢你们的劳动！

**Comment by bynil** [comment]
没有明白你的意思。

"_index": "topic_v1",
"_type": "topic",
"_id": "303776",
"_score": 91.0342,

这几个字段不在我提供的 API 列表里，是 ES 搜索时的 meta 信息。原则上说客户端调用时应该忽略掉。按目前的搜索方式，"_index" "_type" 这两个值是固定的。能否提供一个更详尽的示例呢？
